from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_ROOT = PROJECT_ROOT / "data"

COOKING_DATA_DIR = DATA_ROOT / "cooking"
COOKING_SOURCE_DATA_DIR = COOKING_DATA_DIR / "source"
COOKING_GAME_DATA_DIR = COOKING_DATA_DIR / "games"

TASK_ALLOCATION_DATA_DIR = DATA_ROOT / "task_allocation"
TASK_ALLOCATION_SOURCE_DATA_DIR = TASK_ALLOCATION_DATA_DIR / "source"
TASK_ALLOCATION_GAME_DATA_DIR = TASK_ALLOCATION_DATA_DIR / "games"
